apiVersion: v1
kind: Service
metadata:
  name: sports-web-service
spec:
  selector:
    app: sports-web        # 위 deployment의 이름과 똑같아야 연결됨
  ports:
    - protocol: TCP
      port: 80             # 외부에서 접속할 포트 (기본 웹 포트)
      targetPort: 3000     # 내부 Node.js 서버 포트 (우리가 만든 3000번)
  type: LoadBalancer       # 외부 IP를 받기 위한 설정 (AWS, Azure 등 사용 시)